# Generated by Django 4.2.21 on 2026-03-28 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=20)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='List of ingredients')),
                ('preparation_method', models.TextField()),
                ('calories', models.IntegerField(help_text='Calories per serving')),
                ('is_millet_based', models.BooleanField(default=False)),
                ('replaces', models.CharField(blank=True, help_text="What this replaces (e.g., 'white rice')", max_length=200)),
                ('tamil_nadu_region', models.CharField(blank=True, help_text='Specific region if applicable', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('blood_group', models.CharField(max_length=5)),
                ('diabetes_type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('gestational', 'Gestational')], max_length=20)),
                ('years_since_diagnosis', models.IntegerField()),
                ('family_history', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDietLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=200)),
                ('meal_time', models.DateTimeField(auto_now_add=True)),
                ('portion_size', models.CharField(help_text="e.g., '1 cup', '2 chapatis'", max_length=50)),
                ('calories_consumed', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('diet_suggestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diabetes_tracker.dietsuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calories', models.IntegerField(default=0)),
                ('breakfast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast_plans', to='diabetes_tracker.dietsuggestion')),
                ('dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner_plans', to='diabetes_tracker.dietsuggestion')),
                ('lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch_plans', to='diabetes_tracker.dietsuggestion')),
                ('snacks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snack_plans', to='diabetes_tracker.dietsuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
