# Generated by Django 5.2 on 2026-03-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucoserecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='exercise',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='meal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='medication',
            field=models.CharField(max_length=100),
        ),
    ]
