# Generated by Django 6.0.2 on 2026-03-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_bprecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BPRecord',
        ),
    ]
