# Generated by Django 6.0.3 on 2026-03-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_bprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bprecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bprecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bprecord',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='blood_sugar',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='exercise',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='meal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='medication',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
