# Generated by Django 6.0.3 on 2026-03-07 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_bprecord_notes_alter_bprecord_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bprecord',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='glucoserecord',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Glucose Record', 'verbose_name_plural': 'Glucose Records'},
        ),
        migrations.RemoveField(
            model_name='glucoserecord',
            name='blood_sugar',
        ),
        migrations.RemoveField(
            model_name='glucoserecord',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='glucoserecord',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='glucoserecord',
            name='medication',
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='activity_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Activity Duration (minutes)'),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('walking', 'Walking'), ('running', 'Running/Jogging'), ('yoga', 'Yoga'), ('gym', 'Gym/Weight Training'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='food_notes',
            field=models.TextField(blank=True, verbose_name='Food Description'),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='glucose_level',
            field=models.FloatField(default=100, verbose_name='Glucose Level (mg/dL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='insulin_dose',
            field=models.FloatField(blank=True, null=True, verbose_name='Insulin Dose (units)'),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('none', 'No Meal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='medication_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Additional Comments'),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='reading_type',
            field=models.CharField(choices=[('fasting', 'Fasting (before breakfast)'), ('before_meal', 'Before Meal'), ('after_meal', 'After Meal'), ('random', 'Random'), ('bedtime', 'Bedtime'), ('night', 'Night (2-3 AM)')], default='random', max_length=20),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='symptoms',
            field=models.CharField(blank=True, help_text='Comma-separated symptoms', max_length=100),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bprecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bprecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('glucose_test', 'Blood Glucose Test'), ('medication', 'Take Medication'), ('insulin', 'Insulin Injection'), ('meal', 'Meal Time'), ('exercise', 'Physical Activity'), ('doctor_appointment', 'Doctor Appointment'), ('refill', 'Prescription Refill')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=10)),
                ('reminder_time', models.TimeField()),
                ('days_of_week', models.CharField(blank=True, help_text='Comma-separated days (0-6, 0=Monday)', max_length=50)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('medication_name', models.CharField(blank=True, max_length=200)),
                ('medication_dosage', models.CharField(blank=True, max_length=100)),
                ('test_condition', models.CharField(blank=True, help_text='e.g., before_meal, after_meal, fasting', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('smart_reminder', models.BooleanField(default=False, help_text='Reminder based on glucose patterns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('in_app', 'In-App Notifications'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.reminder')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
