# Generated by Django 6.0.3 on 2026-03-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_bprecord_options_alter_glucoserecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='notify_email',
            field=models.BooleanField(default=False, help_text='Send email'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='notify_in_app',
            field=models.BooleanField(default=True, help_text='Show in-app notification'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='notify_sms',
            field=models.BooleanField(default=False, help_text='Send SMS'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='notify_whatsapp',
            field=models.BooleanField(default=False, help_text='Send WhatsApp'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='override_quiet_hours',
            field=models.BooleanField(default=False, help_text='Send even during quiet hours'),
        ),
    ]
