# Generated by Django 6.0.3 on 2026-03-11 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_add_reminder_notification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='When to start this reminder'),
        ),
    ]
