# Generated by Django 6.0 on 2026-03-16 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_reminder_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glucoserecord',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='activity_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='food_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='insulin_dose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='symptoms',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='notify_in_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='notify_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='override_quiet_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='smart_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='test_condition',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
