# Generated by Django 5.2 on 2026-03-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_glucoserecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='carrier',
            field=models.CharField(blank=True, choices=[('airtel', 'Airtel'), ('jio', 'Jio'), ('vi', 'Vi (Vodafone Idea)'), ('bsnl', 'BSNL'), ('other', 'Other')], max_length=20),
        ),
    ]
