# Generated by Django 6.0.3 on 2026-03-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_bloodsugarrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('diet', 'Diet & Nutrition'), ('exercise', 'Physical Activity'), ('medication', 'Medication'), ('foot_care', 'Foot Care'), ('glucose', 'Glucose Monitoring'), ('general', 'General Health')], max_length=20)),
                ('content', models.TextField(help_text='Tip content for text display')),
                ('audio_url', models.URLField(blank=True, help_text='URL to audio file (MP3)')),
                ('duration', models.CharField(blank=True, help_text='Audio duration', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Health Tip',
                'verbose_name_plural': 'Health Tips',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MythFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myth', models.CharField(max_length=300)),
                ('fact', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Detailed explanation')),
                ('category', models.CharField(blank=True, help_text='e.g., Diet, Medication, Exercise', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Myth & Fact',
                'verbose_name_plural': 'Myths & Facts',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_type', models.CharField(choices=[('insulin', 'Insulin Injection Demo'), ('foot_care', 'Foot Care Demo'), ('cooking', 'Healthy Cooking Guide'), ('glucose_monitoring', 'Glucose Monitoring'), ('exercise', 'Exercise Guide')], max_length=20)),
                ('youtube_url', models.URLField(help_text='YouTube video URL')),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, help_text='Video duration, e.g., 5:30', max_length=50)),
                ('thumbnail', models.URLField(blank=True, help_text='Thumbnail image URL')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video Tutorial',
                'verbose_name_plural': 'Video Tutorials',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
