# Generated by Django 6.0.3 on 2026-03-23 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_remove_userprofile_village_userprofile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='caregiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='tracker.userprofile'),
        ),
    ]
