# Generated by Django 5.2 on 2026-03-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_notificationpreference_carrier'),
        ('tracker', '0012_remove_userprofile_village_userprofile_region'),
    ]

    operations = [
    ]
