# Generated by Django 6.0.3 on 2026-03-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_userprofile_caregiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='caregiver',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='caregiver',
            field=models.ManyToManyField(blank=True, related_name='patients', to='tracker.userprofile'),
        ),
    ]
