# Generated by Django 6.0.3 on 2026-03-31 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_healthtip_mythfact_videotutorial'),
        ('tracker', '0013_merge_20260324_2144'),
    ]

    operations = [
    ]
