# Generated by Django 6.0.3 on 2026-03-24 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_userprofile_email_userprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='push_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='whatsapp_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='notify_sms',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='notify_whatsapp',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='override_quiet_hours',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='smart_reminder',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='test_condition',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='caregiver',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('health_worker', 'Health Worker')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CaregiverLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_name', models.CharField(max_length=150)),
                ('caregiver_phone', models.CharField(max_length=15)),
                ('caregiver_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_links', to='tracker.userprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links', to='tracker.userprofile')),
            ],
        ),
    ]
