# Generated by Django 6.0.3 on 2026-03-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_remove_notificationpreference_push_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_skipped_caregiver',
            field=models.BooleanField(default=False),
        ),
    ]
