# Generated by Django 6.0.3 on 2026-03-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_merge_20260324_2144'),
        ('tracker', '0018_alter_userprofile_role'),
    ]

    operations = [
    ]
