# Generated by Django 6.0.3 on 2026-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_merge_20260331_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
