# Generated by Django 6.0.3 on 2026-03-31 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_notificationpreference_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('health_worker', 'Health Worker')], default='patient', max_length=20),
        ),
        migrations.CreateModel(
            name='CaregiverMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('check_glucose', '🩸 Please check your glucose'), ('take_medicine', '💊 Please take your medicine'), ('drink_water', '💧 Please drink water'), ('rest', '🛏 Please rest'), ('see_doctor', '🏥 Please see a doctor soon'), ('custom', '📝 Custom message')], default='check_glucose', max_length=20)),
                ('custom_text', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='tracker.userprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_messages', to='tracker.userprofile')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CaregiverNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_written', to='tracker.userprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_notes', to='tracker.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('check_sugar', '🩸 Please check your blood sugar'), ('take_medicine', '💊 Please take your medicine'), ('drink_water', '💧 Please drink water'), ('call_me', '📞 Please call me'), ('see_doctor', '🏥 Please visit a doctor'), ('emergency', '🚨 Emergency – contact me immediately'), ('custom', '✏️ Custom message')], max_length=20)),
                ('custom_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_alerts', to='tracker.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_alerts', to='tracker.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
